---
abstract: 'alternative warn and die for modules'
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.94, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Carp
no_index:
  directory:
    - t
    - inc
requires:
  Config: '0'
  Exporter: '0'
  ExtUtils::MakeMaker: '0'
  IPC::Open3: '1.0103'
  Test::More: '0'
  overload: '0'
  parent: '0'
  strict: '0'
  warnings: '0'
version: '1.3301'
